### ISSUE TITLE
How do I change ca.pem by ca-old.pem for instance

### ISSUE THREAD

**Issue by AlbanAndrieu** [andrewrothstein/ansible-tls#1]
https://github.com/andrewrothstein/ansible-tls/blob/773470455712670ba534db013f7ecf60c7f7caaf/defaults/main.yml#L20

How do I change ca.pem by ca-old.pem for instance when using https://github.com/andrewrothstein/ansible-trust-ca ?

Before I was able to change name with trust_ca_pki_prefix: ca-old for instance

```yaml
- name: Install CA root certificate
  hosts: jenkins-slaves
  gather_facts: false
  remote_user: root
  check_mode: no
#  ignore_errors: yes
  become: true

  roles:
    - role: ssl.ca-certificate 
      trust_ca_pki_prefix: ca-old
      trust_ca_cert_prefix: ca-old
      trust_ca_pki_dir: '~/pki'
      trust_ca_cacert_remote_src: yes

    - role: ssl.ca-certificate
      trust_ca_pki_prefix: ca-new
      trust_ca_pki_dir: '~/pki'
      trust_ca_cacert_remote_src: yes
```
